#!/bin/bash

# bash_exports

# Make vim the default editor
export EDITOR="vim"

# Ignore duplicate commands in the history
export HISTCONTROL=ignoredups

# Increase the maximum number of lines contained in the history file
# (default is 500, -1 for unlimited)
export HISTFILESIZE=-1

# Increase the maximum number of commands to remember
# (default is 500)
export HISTSIZE=1000000

# Don't clear the screen after quitting a manual page
export MANPAGER="less -X"

# Make new shells get the history lines from all previous
# shells instead of the default "last window closed" history
export PROMPT_COMMAND="history -a; $PROMPT_COMMAND"
