" .gvimrc

" Hide the MacVim toolbar
set go-=T
" Always display the tab bar
set showtabline
" Turn off the blinking cursor in normal mode
set gcr=n:blinkon0
" Set 5px space between lines
set linespace=5
" Set GUI font
set guifont=Monaco:h14
