#!/bin/bash

run_help() {

cat <<EOT

OS X dotfiles - Nicolas Gallagher - http://nicolasgallagher.com/

Usage: $(basename "$0") [options]

Options:
    --no-packages   skips installation and update of packages
    --no-update     skips updating the repo and submodules

Documentation can be found at https://github.com/necolas/dotfiles/

Copyright (c) Nicolas Gallagher
Licensed under the MIT license."
EOT

}
