#!/bin/bash

# Check for npm
if test ! $(which npm)
then
  echo "  x npm not found. Please install Node.js via Homebrew or from http://nodejs.org/"
  exit
else
  echo "  + npm found."
fi

# Install everything else
npm install bower -g
npm install grunt -g
