#!/bin/bash

cd "${HOME}/.dotfiles"

# Pull down the latest changes.
# git pull origin master

# Check out submodules.
git submodule --quiet update --init

# Install Homebrew formulae.
bash script/homebrew

cd "${OLDPWD}"

function link() {
    # Force create/replace the symlink.
    ln -fs "${HOME}/.dotfiles/${1}" "${HOME}/${2}"
}

function mirrorfiles() {
    # Copy `.gitconfig`.
    # Any global git commands in `~/.bash_profile.local` will be written to
    # `.gitconfig`. This prevents them being committed to the repository.
    rsync -avz --quiet ${HOME}/.dotfiles/git/gitconfig  ${HOME}/.gitconfig

    # Force remove the vim directory if it's already there.
    if [ -e "${HOME}/.vim" ]; then
        rm -rf "${HOME}/.vim"
    fi

    # Create the necessary symbolic links between the `.dotfiles` and `HOME`
    # directory. The `bash_profile` sources other files directly from the
    # `.dotfiles` repository.
    link "bash/bashrc"        ".bashrc"
    link "bash/bash_profile"  ".bash_profile"
    link "bash/inputrc"       ".inputrc"
    link "git/gitattributes"  ".gitattributes"
    link "git/gitignore"      ".gitignore"
    link "vim"                ".vim"
    link "vim/gvimrc"         ".gvimrc"
    link "vim/vimrc"          ".vimrc"

    echo "Dotfiles update complete"
}

read -p "This will overwrite some existing files in your home directory. Are you sure? (y/n) " -n 1

echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    mirrorfiles
    source ~/.bash_profile
fi
