# .bash_profile

# Local and private settings not under version control (e.g. git credentials)
FILES="$HOME/.bash_profile.local"
# Exports
FILES="$FILES $HOME/.dotfiles/bash/exports"
# Aliases
FILES="$FILES $HOME/.dotfiles/bash/aliases"
# Functions
FILES="$FILES $HOME/.dotfiles/bash/functions"
# Custom Bash prompt
FILES="$FILES $HOME/.dotfiles/bash/bash_prompt"
# Git Bash completion (comes with Homebrew git installation)
FILES="$FILES `brew --prefix`/etc/bash_completion.d/git-completion.bash"

# Source all readable files in FILES
for file in $FILES
do
    [ -r "$file" ] && source "$file"
done

# Load RVM into a shell session *as a function*
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"

# Case-insensitive globbing (used in pathname expansion)
shopt -s nocaseglob

# Append to the Bash history file, rather than overwriting it
shopt -s histappend

# Autocorrect typos in path names when using `cd`
shopt -s cdspell
