# .bash_profile

# Local and private settings not under version control (e.g. git credentials)
[ -r "$HOME/.bash_profile.local" ] && source "$HOME/.bash_profile.local"
# Exports
[ -r "$HOME/.dotfiles/bash/exports" ] && source "$HOME/.dotfiles/bash/exports"
# Aliases
[ -r "$HOME/.dotfiles/bash/aliases" ] && source "$HOME/.dotfiles/bash/aliases"
# Functions
[ -r "$HOME/.dotfiles/bash/functions" ] && source "$HOME/.dotfiles/bash/functions"
# Custom bash prompt
[ -r "$HOME/.dotfiles/bash/bash_prompt" ] && source "$HOME/.dotfiles/bash/bash_prompt"

# Load RVM into a shell session *as a function*
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"

# Append to the bash history file, rather than overwriting it
shopt -s histappend

