#!/bin/bash

# Exports

# Make vim the default editor
export EDITOR="vim"
# Don't clear the screen after quitting a manual page
export MANPAGER="less -X"
# Larger bash history (allow 32³ entries; default is 500)
export HISTSIZE=32768
export HISTFILESIZE=$HISTSIZE
export HISTCONTROL=ignoredups
# Make some commands not show up in history
export HISTIGNORE="ls:ls *:cd:cd -:pwd;exit:date:* --help"

# Move to the beginning of PATH so that it always take precedence over /usr/bin
if [ -d "/usr/local/bin" ]; then
    PATH="/usr/local/bin:$PATH"
fi

declare -a bins=(
    "/usr/bin"
    "$HOME/bin"
    "$HOME/.dotfiles/bin"
    "$HOME/.rvm/bin"
    "$(brew --prefix coreutils)/libexec/gnubin" # Add brew-installed GNU core utilities bin
    "$(brew --prefix)/share/npm/bin" # Add npm-installed package bin
)

# If these bins exist, then add them to the PATH
for index in ${!bins[*]}
do
    if [ -d ${bins[$index]} ]; then
        PATH="$PATH:${bins[$index]}"
    fi
done

unset bins

export PATH
